name: Execute script

description: Exectues a remote script

inputs:
  name: 
    description: 'The name of the script you want to execute'
    required: true
  params: 
    description: 'The params to execute the script with'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - run: curl -o ./${{ inputs.name }}.sh https://raw.githubusercontent.com/appex-org/ci-workflows/main/scripts/${{ inputs.name }}.sh 
      shell: bash
    - run: chmod +x ./${{ inputs.name }}.sh
      shell: bash
    - run: ./${{ inputs.name }}.sh ${{ inputs.params }}
      shell: bash
