name: Flutter integration tests

on:
  workflow_call:
    inputs:
      flutter-version:
        description: "Sets the current node version"
        default: "3.3.4"
        required: false
        type: string
      ios-device:
        description: "The IOS device you want the tests to run on"
        default: "iPhone 11"
        required: false
        type: string
      run-ios-tests:
        description: "Set to true to run the IOS tests"
        default: false
        required: false
        type: boolean
      run-android-tests:
        description: "Set to true to run the Android tests"
        default: false
        required: false
        type: boolean

jobs:
  ios-tests:
    runs-on: macos-latest
    if: ${{ inputs.run-ios-tests }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: flutter pub get
      - name: Start simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ inputs.ios-device }}
      - run: flutter test integration_test

  android-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.run-android-tests }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test
