name: Flutter integration tests

on:
  workflow_call:
    inputs:
      flutter-version:
        description: "Sets the current node version"
        default: "3.3.4"
        required: false
        type: string

jobs:
  ios-tests:
    runs-on: macos-11
    steps:
      - name: Start simulator
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: flutter pub get
      - run: flutter test integration_test
