name: Flutter build and verify

on:
  workflow_call:
    inputs:
      flutter-version:
        description: "Sets the current node version"
        default: "3.3.4"
        required: false
        type: string
    secrets:
      env-config:
        description: 'The environment config for the app'
        required: false

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - uses: actions/checkout@v3
      - name: Create env
        run: echo '${{ secrets.env-config }}' >> '.env'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
