name: Node publish package

on:
  workflow_call:
    inputs:
      node-version: 
        description: 'Sets the current node version'
        default: '16'
        required: false
        type: string
      typescript-build:
        description: 'Set to true to build typescript'
        default: true
        required: false
        type: boolean
      only-version: 
        description: 'Set to true if the package is only to be versioned and not published'
        default: false
        required: false
        type: boolean
    secrets:
      node-auth-token:
        description: 'The node auth token'
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - if: ${{ inputs.typescript-build }}
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - uses: appex-org/ci-workflows/.github/actions/create-npmrc@main
        with:
          auth-token: ${{ secrets.node-auth-token }}
          scope: "@appex-development"
      - uses: appex-org/ci-workflows/.github/actions/execute-script@main
        with: 
          name: publish_package
          params: ${{ inputs.only-version }}
        env:
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_USERNAME: ${{ github.actor }}
