name: Node publish package

on:
  workflow_call:
    inputs:
      node-version: 
        description: 'Sets the current node version'
        default: '16'
        required: false
        type: string
      only-version: 
        description: 'Set to true if the package is only to be versioned and not published'
        default: true
        required: false
        type: boolean
    secrets:
      node-auth-token:
        description: 'The node auth token'
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@appex'
      - run: npm ci
      - run: ./scripts/publish_package.sh ${{ inputs.only-version }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_USERNAME: ${{ github.actor }}