name: Terraform plan

on:
  workflow_call:
    inputs:
      backend-config:
        description: 'The backend config file'
        required: true
        type: string
    secrets:
      gcp-credentials:
        description: 'The GCP service account credentials'
        required: true
      env-config:
        description: 'The environment config'
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.gcp-credentials }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Create environment
        run: echo ${{ secrets.env-config }} >> main.tfvars
      - run: terraform init -backend-config=${{ inputs.backend-config }}
      - run: terraform fmt -check
      - run: terraform plan -var-file='main.tfvars'
