name: Terraform deploy

on:
  workflow_call:
    inputs:
      backend-config:
        description: 'The backend config file'
        required: true
        type: string
      only-plan:
        description: 'Set to true to only plan a deployment'
        default: false
        required: false
        type: boolean
      typescript:
        description: "Set to true to download packaged code"
        default: true
        required: false
        type: boolean
    secrets:
      gcp-credentials:
        description: 'The GCP service account credentials'
        required: true
      env-config:
        description: 'The environment config'
        required: true

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.gcp-credentials }}
    steps:
      - uses: actions/checkout@v3

      - if: ${{ inputs.typescript }}
        name: Build
        run: npm run build

      - uses: hashicorp/setup-terraform@v2

      - name: Create environment
        run: cd infrastructure && echo '${{ secrets.env-config }}' >> main.tfvars

      - name: terraform init
        run: cd infrastructure && terraform init -backend-config=${{ inputs.backend-config }}

      - name: terraform validate
        run: cd infrastructure && terraform validate

      - name: terraform fmt
        run: cd infrastructure && terraform fmt -check -recursive

      - name: terraform plan
        run: cd infrastructure && terraform plan -var-file='main.tfvars'

      - if: ${{ !inputs.only-plan }}
        name: terraform apply
        run: cd infrastructure && terraform apply -var-file='main.tfvars' -auto-approve
