name: Terraform deploy

on:
  workflow_call:
    inputs:
      backend-config:
        description: 'The backend config file'
        required: true
        type: string
      only-plan:
        description: 'Set to true to only plan a deployment'
        default: false
        required: false
        type: boolean
    secrets:
      gcp-credentials:
        description: 'The GCP service account credentials'
        required: true
      env-config:
        description: 'The environment config'
        required: true

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.gcp-credentials }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ../dist
      - uses: hashicorp/setup-terraform@v2
      - name: Create environment
        run: echo '${{ secrets.env-config }}' >> main.tfvars
      - run: terraform init -backend-config=${{ inputs.backend-config }}
      - run: cd .. && ls
      - run: terraform fmt -check
      - run: terraform plan -var-file='main.tfvars'
      - if: ${{ inputs.only-plan }} != true
        run: terraform apply -var-file='main.tfvars' -auto-approve
